In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [13]:
arr=np.array([[1,'Delhi'],[2,'Mumbai'],[3,'Mumbai'],[4,'Delhi'],[5,'Kolkata'],[6,'Delhi'],[7,'Delhi'],[8,'Delhi'],[9,'Mumbai'],[10,'Kolkata']])
city = arr[:, 1].reshape(-1, 1)

In [14]:
ordinal_city= city.copy()
onehot_city= city.copy()

In [15]:
ordinal_encoder = OrdinalEncoder()
ordinal_encoded = ordinal_encoder.fit_transform(ordinal_city)

In [17]:
print("Original City Column:\n", city_column)
print("\nOrdinal Encoded Cities:\n", ordinal_encoded)

Original City Column:
 [['Delhi']
 ['Mumbai']
 ['Mumbai']
 ['Delhi']
 ['Kolkata']
 ['Delhi']
 ['Delhi']
 ['Delhi']
 ['Mumbai']
 ['Kolkata']]

Ordinal Encoded Cities:
 [[0.]
 [2.]
 [2.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [2.]
 [1.]]


In [21]:
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(onehot_city)

F:\anaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [22]:
print("\nOne Hot Encoded Cities:\n", onehot_encoded)


One Hot Encoded Cities:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
